name: chatorrent
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  network_plugin_go_ffi:
    path: plugins/network_plugin_go_ffi
  sqlite3: ^2.4.6
  sqlite3_flutter_libs: ^0.5.24
  protobuf: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
