/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package network_plugin */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h>

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 4 "network_plugin.go"

#if !_WIN32
#define __declspec(dllexport)
#endif

#include <stdlib.h>
#include "register_callback.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef size_t GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
#ifdef _MSC_VER
#include <complex.h>
typedef _Fcomplex GoComplex64;
typedef _Dcomplex GoComplex128;
#else
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;
#endif

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


// CreateSession for offer side to create a session
extern __declspec(dllexport) char* CreateSession(int SessionID);

// Offer return offer BASE64
extern __declspec(dllexport) char* Offer(int SessionID);

// JoinSession for answer side to join a session described by SDP
// 假定sdpBase64是\0结尾字符串
extern __declspec(dllexport) char* JoinSession(int SessionID, char* sdpBase64);

// Answer can be called after JoinSession
extern __declspec(dllexport) char* Answer(int SessionID);

// ConfirmAnswer confirms a session description
// 假定sdpBase64是\0结尾字符串
extern __declspec(dllexport) char* ConfirmAnswer(int SessionID, char* sdpBase64);

// Send add data to send queue, it is not a obstructive function
extern __declspec(dllexport) char* Send(int SessionID, char* data, int size);

// Ready return a list of received messages and where are they from
// 计划使用json返回
extern __declspec(dllexport) char* Ready();

// DropSession allow user to drop a session
// Warning: don't call DropSession easily, because it is very slow; not-used session will be shutdown automatically
extern __declspec(dllexport) char* DropSession(int SessionID);

// ReloadConfig will force SessionManager reload config from conf.json
// warning: it may not work immediately
extern __declspec(dllexport) char* ReloadConfig();

// Discard a SessionManager
extern __declspec(dllexport) char* Discard();
extern __declspec(dllexport) int sum(int a, int b);
extern __declspec(dllexport) int sum_long_running(int a, int b);
extern __declspec(dllexport) void registerCallback(void* binop);
extern __declspec(dllexport) void start_fetch();
extern __declspec(dllexport) char* getHTTPHeaderFirstLine(char* cUrl);

// Free the memory allocated for the C string
extern __declspec(dllexport) void freeCString(char* cstr);
extern __declspec(dllexport) void enforce_binding();

#ifdef __cplusplus
}
#endif
